# Generated by Django 2.1.7 on 2019-03-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
    ]
