# Generated by Django 2.1.7 on 2019-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_edital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='edital',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='avaliador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='usuario',
        ),
        migrations.AddField(
            model_name='avaliador',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='data_publicacao',
            field=models.DateField(verbose_name='Data de publicação'),
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
