# Generated by Django 2.1.7 on 2019-03-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_edital', '0002_auto_20190313_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edital',
            options={'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
    ]
