# Generated by Django 2.1.7 on 2019-03-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_edital', '0003_auto_20190313_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivonotazero',
            old_name='descriaco',
            new_name='descricao',
        ),
    ]
